### ISSUE TITLE
Copyright Symbol Causes the CardMachine to Crash

### ISSUE THREAD

**Issue by n-a-larson** [coandco/TSSSF-Frontend#20]
...When used in flavor text or on the copyright line. Not a problem in other fields.

**Comment by Latent-Logic** [comment]
```
Card build failed! Attempting to build card u'Pony``malefemale!unicorn`\xa9`\xa9`\xa9`\xa9`web-grey`WEB CARD; TSSSF by Horrible People Games. Art by Unknown.' u'\xa9' 
Traceback (most recent call last): 
File "single_card.py", line 138, in <module> args.returntype, IMGURTITLE, IMGURDESC) 
File "single_card.py", line 87, in make_single_card im["vassal"]) = TSSSF_CardGen.BuildSingleCard(card_line) 
File "CardMachine/TSSSF_CardGen.py", line 274, in BuildSingleCard im_bleed = PickCardFunc(tags[TYPE], tags) 
File "CardMachine/TSSSF_CardGen.py", line 341, in PickCardFunc return MakePonyCard(data) 
File "CardMachine/TSSSF_CardGen.py", line 605, in MakePonyCard return MakePonyCardPON(card) 
File "CardMachine/TSSSF_CardGen.py", line 628, in MakePonyCardPON text_size = FlavorText(image, tags[FLAVOR], ColorDict["Pony flavor"]) 
File "CardMachine/TSSSF_CardGen.py", line 503, in FlavorText padline=True, 
File "CardMachine/PIL_Helper.py", line 111, in AddText line = " {0} ".format(line) 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa9' in position 0: ordinal not in range(128) 
Failed to build single card u'Pony``malefemale!unicorn`\xa9`\xa9`\xa9`\xa9`web-grey`WEB CARD; TSSSF by Horrible People Games. Art by Unknown.'
```

**Comment by Latent-Logic** [comment]
Fixed on the live site with the above change.
